stages:          # List of stages for jobs, and their order of execution
  - mirror


mirror-job:       # This job runs in the build stage, which runs first.
  stage: mirror
  script:
    - git config --global credential.username imajeetyadav
    - git config --global core.askPass /cred-helper.sh
    - git config --global credential.helper cache
    - git remote add mirror https://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@github.com/imAjeetYadav/Gitlab-mirror-POC.git
    - git remote get-url --push mirror 
    - git push --force mirror HEAD:main


