stages:          # List of stages for jobs, and their order of execution
  - mirror


mirror-job:       # This job runs in the build stage, which runs first.
  stage: mirror
  script:
    - git fetch --all
    - git push -f  --mirror https://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@github.com/imAjeetYadav/Gitlab-mirror-POC.git


