stages:          # List of stages for jobs, and their order of execution
  - mirror


mirror-job:       # This job runs in the build stage, which runs first.
  stage: mirror
  script:
    # - git config --global credential.username imajeetyadav
    # - git config --global core.askPass /cred-helper.sh
    # - git config --global credential.helper cache
    # - git remote add mirror https://${TOKEN}@github.com/imAjeetYadav/Gitlab-mirror-POC.git
    # - git remote get-url --push mirror 
    # - git push --force mirror 
    - mkdir mirror && cd mirror
    - git clone --bare https://gitlab.com/imajeetyadav/mirror-poc.git
    - git push --mirror https://${TOKEN}@github.com/imAjeetYadav/Gitlab-mirror-POC.git
    # - git push --force --delete main --mirror
   # - git push origin --force HEAD:main
    # - git push origin --force



