stages:          # List of stages for jobs, and their order of execution
  - mirror


mirror-job:       # This job runs in the build stage, which runs first.
  stage: mirror
  script:
    # - git config --global credential.username imajeetyadav
    # - git config --global core.askPass /cred-helper.sh
    # - git config --global credential.helper cache
    # - git remote add mirror https://${TOKEN}@github.com/imAjeetYadav/Gitlab-mirror-POC.git
    # - git remote get-url --push mirror 
    # - git push --force mirror 
    
    - mkdir temp-dir && cd temp-dir
    - git clone  $CI_REPOSITORY_URL
    - git branch -a
    - git fetch --all
    - git remote rm origin
    - echo $TOKEN
    - git config user.name "LogitSocial"
    - git config user.email "yadavajeetak47@gmail.com"
    # - git config user.password 
    # - git remote add origin https://$TOKEN@github.com/LogitSocial/mirror-poc.git
    - git push -f https://$TOKEN@github.com/LogitSocial/mirror-poc.git --all

    # - git fetch --all
    # - git config  user.name "imAjeetYadav" --replace-all
    # - git config  user.email "ajeetyadav164@gmail.com" --replace-all
    # - git config --global url."https://api:$TOKEN@github.com/".insteadOf "https://github.com/"
    # - git config --global url."https://ssh:$TOKEN@github.com/".insteadOf "ssh://git@github.com/"
    # - git config --global url."https://git:$TOKEN@github.com/".insteadOf "git@github.com:"
    # - git config --global core.askPass /cred-helper.sh
    # - git config --global credential.helper cache
    # - git remote add mirror https://imAjeetYadav:$TOKEN@github.com/imAjeetYadav/Gitlab-mirror-POC-.git
    # - git clone --bare https://gitlab.com/imajeetyadav/mirror-poc.git
    # - git push -f --mirror mirror
    # - git push --force --delete main --mirror
   # - git push origin --force HEAD:main
    # git push --force mirror HEAD:main


