stages:          # List of stages for jobs, and their order of execution
  - mirror


mirror-job:       # This job runs in the build stage, which runs first.
  stage: mirror
  script:

    - mkdir temp-dir 
    - env
    - git clone  $CI_REPOSITORY_URL temp-dir
    - cd temp-dir
    - git branch -a
    - git fetch --all
    - git remote rm origin
    # - echo $TOKEN   
    # - git remote add origin 
    - git push -f https://LogitSocial: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@github.com/LogitSocial/mirror-poc.git --all



